name: careqar
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+5

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_lints: ^5.0.0
  fluttertoast: ^8.2.12
  photo_view: ^0.15.0
  shared_preferences: ^2.5.2
  collection: ^1.18.0
  image: ^4.0.17
  device_info_plus: ^11.3.2
#  google_maps_place_picker_mb: ^3.1.2
  package_info_plus: ^4.1.0
  geolocator: ^13.0.2
  flutter_cache_manager: ^3.4.1
  introduction_screen: ^3.1.17
  flutter_facebook_auth: ^7.1.1
  google_sign_in: ^6.2.2
  firebase_analytics: ^11.4.4
  flutter_screenutil: ^5.9.3
  firebase_dynamic_links: ^6.1.4   # discontinued
  share_plus: ^10.1.4
  path_provider: ^2.1.5
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  firebase_auth: ^5.5.1
  permission_handler: ^11.4.0
  crypto: ^3.0.6
  sign_in_with_apple: ^6.1.4
  intl_phone_number_input: ^0.7.4
  #  firebase_remote_config: ^3.0.15
  flutter_staggered_grid_view: ^0.7.0
  flutter_vector_icons: ^2.0.0
  pin_code_fields: ^8.0.1
  file_picker: ^9.0.2
  url_launcher: ^6.3.1
  get: ^4.7.2
  image_picker: ^1.1.2
  http: ^1.3.0
  dio: ^5.8.0+1
  open_file: ^3.5.10
  dartz: ^0.10.1
  timeago: ^3.7.0
  flutter_email_sender: ^7.0.0
  video_player: ^2.9.3
  gif_view: ^0.4.0
  intl: ^0.20.2
  google_maps_flutter: ^2.11.0
  flutter_easyloading: ^3.0.5
  enum_to_string: ^2.2.0
  flutter_countdown_timer: ^4.1.0
  firebase_core: ^3.12.1
  shimmer: ^3.0.0
  flutter_exif_rotation: ^0.5.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  image_cropper: ^9.1.0
  device_preview: ^1.2.0
  firebase_core_platform_interface: ^5.4.0
  youtube_player_flutter: ^9.1.1
  flutter_pdfview: ^1.4.0
  flutter_widget_from_html: ^0.16.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5
  google_fonts: ^6.2.1
  flutter_svg: ^2.2.0
  marquee: ^2.3.0
  font_awesome_flutter: ^10.9.0
  geocoding: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/ic_icon.png"
  min_sdk_android: 23
  adaptive_icon_background: "assets/icon/old_app_icon.png"
  adaptive_icon_foreground: "assets/icon/old_app_icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/old_app_icon.png
  branding: assets/images/trans.png
  image_dark: assets/icon/ic_icon.png
  color_dark: "#ffffff"
  android_gravity: fill
  android_12:
    image: assets/icon/old_app_icon.png
    color: "#ffffff"
    image_dark: assets/icon/old_app_icon.png
    color_dark: "#ffffff"
    branding: assets/images/trans.png
  android: true
  ios: true
  web: false




dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.15

#  change_app_package_name: ^1.4.0
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
    - assets/icon/

  fonts:
    - family: AppFonts
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-LightItalic.ttf
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/Montserrat-ThinItalic.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Thin.ttf

